# Generated by Django 3.1.7 on 2021-04-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pageElementModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('elementName', models.CharField(max_length=20)),
            ],
        ),
    ]
