# Generated by Django 3.1.7 on 2021-04-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAssistantApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='outlierElementModel',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
            ],
        ),
    ]
